spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes[0]:
        id: EMPLOYEE-SERVICE
        uri: lb://EMPLOYEE-SERVICE
        predicates[0]: Path=/api/employees/**
      routes[1]:
        id: DEPARTMENT-SERVICE
        uri: lb://DEPARTMENT-SERVICE
        predicates[0]: Path=/api/departments/**
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true

eureka:
  instance:
    client:
      serverUrl:
        defualtZone: http://localhost:8761/eureka/

server:
  port: 9191


#  routes for employee service