spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employee_db
    username: root
    password: Harsh@4902

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: EMPLOYEE-SERVICE

server:
  port: 8081

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/