spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Harsh4902/config-server-repo
          clone-on-start: true
          default-label: master

server:
  port: 8888

eureka:
  instance:
    client:
      serverUrl:
        defualtZone: http://localhost:8761/eureka/

